# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bronn_shit.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.buttonBase = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBase.setGeometry(QtCore.QRect(0, 470, 401, 51))
        self.buttonBase.setObjectName("buttonBase")
        self.buttonEdit = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEdit.setGeometry(QtCore.QRect(404, 470, 401, 51))
        self.buttonEdit.setObjectName("buttonEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.buttonBase.clicked.connect(self.show_base)
        self.buttonEdit.clicked.connect(self.show_modified)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonBase.setText(_translate("MainWindow", "Base"))
        self.buttonEdit.setText(_translate("MainWindow", "Edit"))

    def show_base(self):
        self.label.setPixmap(QtGui.QPixmap("bronn_shit.jpg"))

    def show_modified(self):
        self.label.setPixmap(QtGui.QPixmap("cate.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
