# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bronn_test_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 686)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Pic = QtWidgets.QLabel(self.centralwidget)
        self.Pic.setGeometry(QtCore.QRect(0, 0, 801, 391))
        self.Pic.setText("")
        self.Pic.setPixmap(QtGui.QPixmap("bronn_shit.jpg"))
        self.Pic.setAlignment(QtCore.Qt.AlignCenter)
        self.Pic.setObjectName("Pic")
        self.ScaleContent = QtWidgets.QCheckBox(self.centralwidget)
        self.ScaleContent.setGeometry(QtCore.QRect(10, 480, 91, 31))
        self.ScaleContent.setObjectName("ScaleContent")
        self.x_slider = QtWidgets.QSlider(self.centralwidget)
        self.x_slider.setGeometry(QtCore.QRect(130, 430, 631, 16))
        self.x_slider.setMinimum(-100)
        self.x_slider.setMaximum(100)
        self.x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.x_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x_slider.setTickInterval(10)
        self.x_slider.setObjectName("x_slider")
        self.y_slider = QtWidgets.QSlider(self.centralwidget)
        self.y_slider.setGeometry(QtCore.QRect(130, 500, 631, 16))
        self.y_slider.setMinimum(-100)
        self.y_slider.setMaximum(100)
        self.y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.y_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.y_slider.setTickInterval(10)
        self.y_slider.setObjectName("y_slider")
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(130, 400, 101, 16))
        self.x_label.setObjectName("x_label")
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(130, 470, 101, 16))
        self.y_label.setObjectName("y_label")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(290, 540, 201, 81))
        self.SaveButton.setObjectName("SaveButton")
        self.Open = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.Open.setGeometry(QtCore.QRect(10, 420, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Open.sizePolicy().hasHeightForWidth())
        self.Open.setSizePolicy(sizePolicy)
        self.Open.setToolTip("")
        self.Open.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Open.setAutoFillBackground(False)
        self.Open.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.Open.setCenterButtons(True)
        self.Open.setObjectName("Open")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ScaleContent.setText(_translate("MainWindow", "Scale Content"))
        self.x_label.setText(_translate("MainWindow", "X crop"))
        self.y_label.setText(_translate("MainWindow", "Y crop"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


# https://www.youtube.com/watch?v=GkgMTyiLtWk&list=PLzMcBGfZo4-lB8MZfHPLTEHO9zJDDLpYj&index=6&ab_channel=TechWithTim