# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_slider.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ScaleContent = QtWidgets.QCheckBox(self.centralwidget)
        self.ScaleContent.setGeometry(QtCore.QRect(10, 480, 91, 31))
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(290, 340, 201, 81))
        self.OpenButton.setObjectName("OpenButton")
        self.ScaleContent.setObjectName("ScaleContent")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(200, 230, 301, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.horizontalSlider.valueChanged.connect(self.v_change)
        self.ScaleContent.clicked.connect(self.checked_change)
        self.OpenButton.clicked.connect(self.open_dialog_box)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.ScaleContent.setText(_translate("MainWindow", "Scale Content"))
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenButton.setText(_translate("MainWindow", "Open"))

    def v_change(self):
        value = str(self.horizontalSlider.value())
        is_checked = self.ScaleContent.isChecked()
        print(value + str(is_checked))

    def checked_change(self):
        print(str(self.ScaleContent.isChecked()))

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        print(filename[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
